# FROM ubuntu:24.04
# RUN apt-get update && apt-get install -y nano
# CMD ["bash"]

# FROM ubuntu:24.04
# CMD ["echo", "Yitzchak Maimon"]

FROM ubuntu:24.04
RUN apt-get update && apt-get install -y python3
CMD ["bash"]
